# This file defines the principal settings for this project

# Definition of the grfs
REPO_NAME           ?= OpenGFX+ Landscape

# This is the filename part common to the grf file, main source file and the tar name
BASE_FILENAME       ?= ogfx-landscape

# Documentation files
DOC_FILES ?= docs/readme.txt docs/license.txt docs/changelog.txt

# Directory structure
SCRIPT_DIR          ?= scripts

# Uncomment in order to make use of gimp scripting. See the file
# for a description of the format
GFX_SCRIPT_LIST_FILES      := src/gfx/water/waterfeatures.xcf2png src/gfx/terrain_grid.xcf2png src/gfx/water/seashores.xcf2png src/gfx/infrastructure/roadrail.xcf2png src/gfx/landscape_objects/landscape_objects.xcf2png
