# This file defines the principal settings for this project

# Definition of the grfs
REPO_NAME           ?= OpenGFX+ Landscape Minus

# This is the filename part common to the grf file, main source file and the tar name
BASE_FILENAME       ?= ogfx-landscape-minus

# Documentation files
DOC_FILES ?= docs/readme.txt docs/license.txt docs/changelog.txt

# Directory structure
SCRIPT_DIR          ?= scripts

# Uncomment in order to make use of gimp scripting. See the file
# for a description of the format
GFX_SCRIPT_LIST_FILES      :=
